### PR TITLE
ashuffle re-write in C++

### PR DESCRIPTION
**Pull request by joshkunz**
This is a complete re-write of ashuffle in (hopefully) idiomatic C++. ashuffle was not getting not-fun to work on as the complexity of various performance fixes and features is increasing. By re-writing in C++ we can leverage the substantially more powerful abstractions provided by C++, and helpful utilities in the C++ stdlib.

This PR contains no feature changes, and was written in a way to specifically prevent observable changes to features. The translation was done file-by-file, and tests were kept as similar as possible.

This change also:
 
* Takes a new dependency on `cmake` in the build system, to support the following two bullets.
* Includes a re-write of ashuffle's unit tests in googletest. googletest is substantially nicer than `libtap` since it supports C++ features "out of the box".
* Takes a dependency on `absl`. This is mainly used for some helpful string formatting utilities not present in the stdlib. I took a dependency on absl instead of a more popular library like boost because I wanted to vendor the library, and I want to keep the dependency set relatively small.

### CODE REVIEW

**Comment by joshkunz** [comment]
While I was trying to set this up, it appears that this C++ re-write only builds with relatively recent clang builds (8.0+). I think that means this PR needs to be blocked on some kind of binary release that will support most users (likely linux x86_64), and then updated build instructions.

**Comment by martinetd** [comment]
On debian stable this fails to build because of meson version, the gcc 8.3.0 provided seems to work ok.
This seems to require meson 52 or higher:
 - 51 failed with `meson.build:5:0: ERROR: Unknown target type "INTERFACE_LIBRARY"` after generating absl stuff, I assume installing it manually instead of using subproject might work around the issue
 - 50 failed with `meson.build:5:0: ERROR: Module cmake does not have method subproject.`, same comment
 - 49 (debian's) failed with `meson.build:3:0: ERROR:  Module "cmake" does not exist`

Thankfully upgrading meson is as simple as cloning and running meson.py from the repo, and that aside building went fine and it seems to work. I half regret no longer having my arm machine to try :)

That aside:
 - (I hadn't updated in ages so change from `--queue_buffer` to `--queue-buffer` broke but can't really blame anyone for that...)
 - I'm surprised no native libmpdclient c++ library exist (class-like interface), but it's not so complicated so meh why not.

**Comment by joshkunz** [comment]
Thanks for trying out the patch @martinetd!

> On debian stable this fails to build because of meson version, the gcc 8.3.0 provided seems to work ok.

Well that's good to know. It was failing with gcc on travis. We're using the C++20 aggregate initialization form (similar to the C99 form) in some places. It looked like GCC didn't have this enabled, but I guess that was an even older version, or I read something wrong.

> This seems to require meson 52 or higher

That's kind-of a bummer. I didn't notice this since we use [52 on Travis](https://github.com/joshkunz/ashuffle-integration-root/commit/104b0dbaf0976208995e2a8905d4b307c0b0c0f9). I think this just provides more evidence that the build is probably too complicated with this change for "just build it yourself" to be the *only* distribution strategy.

I'll take a stab at an x86_64-linux-glibc binary distribution this weekend. If we have that, I think building would become a non-issue for most users, and it would be OK to merge this.

> I'm surprised no native libmpdclient c++ library exist (class-like interface).

I mean, I know at least ncmpcpp has a C++ wrapper around libmpdclient. So others have done it before. But yeah, it is kinda strange there isn't a canonical one. Like you say though, the wrapper isn't *too* bad for ashuffle's use-case, and it makes the unit-tests much cleaner and more hermetic, so I don't feel too bad about this in-house wrapper :)

**Comment by joshkunz** [comment]
Merged and tagged v3.0.0.

**Pull request merged**
